/**
 * 
 */
package lu.itrust.business.ts.model.scale;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.Cacheable;
import jakarta.persistence.CollectionTable;
import jakarta.persistence.Column;
import jakarta.persistence.ElementCollection;
import jakarta.persistence.Entity;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.MapKeyColumn;
import jakarta.persistence.Transient;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import org.springframework.util.StringUtils;

import lu.itrust.business.ts.model.parameter.type.impl.AbstractParameterType;


/**
 * Represents a scale type in the system.
 * This class extends the AbstractParameterType class and provides additional properties and methods specific to scale types.
 */

@Entity
@Cacheable
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@AttributeOverride(name = "id", column = @Column(name = "idScaleType"))
public class ScaleType extends AbstractParameterType {

	@Column(name = "dtAcronym", unique = true)
	private String acronym;

	@ElementCollection
	@MapKeyColumn(name = "dtLocale")
	@Cascade(CascadeType.ALL)
	@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
	@CollectionTable(name = "ScaleTypeTranslations", joinColumns = @JoinColumn(name = "fiScaleType"))
	private Map<String, Translation> translations = new LinkedHashMap<>();

	/**
	 * 
	 */
	public ScaleType() {
	}

	public ScaleType(String name, String acronym) {
		super(name);
		setAcronym(acronym);
	}

	/**
	 * @return the acronym
	 */
	public String getAcronym() {
		return acronym;
	}

	/**
	 * @param acronym
	 *            the acronym to set
	 */
	public void setAcronym(String acronym) {
		this.acronym = acronym;
	}

	/**
	 * @return the translations
	 */
	public Map<String, Translation> getTranslations() {
		return translations;
	}

	/**
	 * @param translations
	 *            the translations to set
	 */
	public void setTranslations(Map<String, Translation> translations) {
		this.translations = translations;
	}

	/**
	 * @param key
	 * @return
	 * @see java.util.Map#get(java.lang.Object)
	 */
	public Translation get(String key) {
		return translations.get(key);
	}

	/**
	 * @param key
	 * @param value
	 * @return
	 * @see java.util.Map#put(java.lang.Object, java.lang.Object)
	 */
	public Translation put(String key, Translation value) {
		return translations.put(key, value);
	}

	/**
	 * @param action
	 * @see java.util.Map#forEach(java.util.function.BiConsumer)
	 */
	public void forEach(BiConsumer<? super String, ? super Translation> action) {
		translations.forEach(action);
	}

	/**
	 * Sets the name of the scale type.
	 *
	 * @param name the name to set
	 */
	@Override
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Returns the display name of the scale type.
	 *
	 * @return the display name as a {@code String}.
	 */
	public String getDisplayName() {
		return StringUtils.capitalize(name.toLowerCase());
	}

	/**
	 * Returns the translated string for the given key.
	 *
	 * @param key the key to look up the translation
	 * @return the translated string if found, otherwise the display name of the scale type
	 */
	public String getTranslate(String key) {
		Translation translation = get(key);
		return translation == null ? getDisplayName() : translation.getName();
	}

	/**
	 * Returns the short name for the given key.
	 *
	 * @param key the key to retrieve the short name for
	 * @return the short name for the given key, or the default short name if the translation is not found
	 */
	public String getShortName(String key) {
		Translation translation = get(key);
		return translation == null ? getShortName() : translation.getShortName();
	}

	/**
	 * Returns the short name of the scale type.
	 * The short name is generated by capitalizing the first three characters of the name,
	 * converting them to lowercase, and appending a period if the name is longer than three characters.
	 *
	 * @return the short name of the scale type
	 */
	public String getShortName() {
		return StringUtils.capitalize(name.length() > 3 ? name.substring(0, 3).toLowerCase() + "." : name);
	}

	
}
