ALTER TABLE `ActionPlan` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `ActionPlanAsset` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `ActionPlanSummary` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `ActionPlanSummaryStandardConformance` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `ActionPlanType` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `Analysis` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `AnalysisExcludeAcronyms` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `AnalysisILRImpactTypes` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `AnalysisStandardMeasures` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `AnalysisSetting` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `AnalysisShareInvitation` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `AnalysisStandard` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `Assessment` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `AssessmentImpacts` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `Asset` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `AssetEdge` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `AssetILRImpactAvailabilities` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `AssetILRImpactConfidentialities` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `AssetILRImpactIntegrities` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `AssetImpact` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `AssetMeasure` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `AssetNode` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `AssetType` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `AssetTypeValue` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `Customer` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `DynamicParameter` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `EmailTemplate` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `EmailValidatingRequest` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `ExternalNotification` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `FormulaValue` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `History` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `IDS` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `IDSSubscribers` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `ILRImpact` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `IlrSoaScaleParameter` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `ImpactParameter` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `ItemInformation` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `Language` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `LevelValue` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `LikelihoodParameter` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `MaturityMeasure` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `MaturityParameter` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `Measure` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `MeasureAssetTypeValue` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `MeasureAssetValue` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `MeasureDescription` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `MeasureDescriptionText` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `MeasureProperties` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `NormalMeasure` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `ParameterType` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `Phase` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `RealValue` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `ReportTemplate` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `ResetPassword` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `RiskAcceptanceParameter` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `RiskInformation` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `RiskProfile` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `RiskProfileExpImpacts` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `RiskProfileMeasures` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `RiskProfileRawImpacts` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `RiskRegister` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `Role` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `ScaleType` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `ScaleTypeTranslations` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `Scenario` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `ScenarioAssetTypeValue` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `ScenarioLinkedAsset` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `SchemaVersion` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `SecurityCriteria` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `SimpleDocument` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `SimpleParameter` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `Standard` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `TicketingSystem` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `TrickLog` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `TrickLogParameters` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `TrickService` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `TSSetting` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `User` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `UserAnalysisRight` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `UserCredential` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `UserCustomer` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `UserRole` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `UserSetting` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `UserSQLite` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `Value` CONVERT TO CHARACTER SET utf8mb4;

ALTER TABLE `WordReport` CONVERT TO CHARACTER SET utf8mb4;