/**
 * 
 */
package lu.itrust.business.TS.model.general;

/**
 * @author eomar
 *
 */
public enum LogAction {
	CREATE, UPDATE, DELETE, CREATE_OR_UPDATE, SWITCH_CUSTOMER, AUTHENTICATE, GIVE_ACCESS, AUTO_GRANT, REMOVE_ACCESS, DENY_ACCESS, RESET_PASSWORD, REQUEST_TO_RESET_PASSWORD, MANAGE, GRANT_ACCESS, INSTALL, RE_INSTALL, START, STOP, RE_START, SUSPEND, RESUME, DOWNLOAD, UPDLOAD, REFRESH, IMPORT, EXPORT, RENAME, CHANGE, MOVE, APPLY, RUN, EXCEUTE, OPEN, ACCESS, READ, SIGN_IN, SIGN_OUT, SIGN_UP
}
