/**
 * 
 */
package lu.itrust.business.TS.model.general;

/**
 * @author eomar
 *
 */
public enum LogAction {
	ACCESS, APPLY, AUTHENTICATE, AUTO_GRANT, CHANGE, CREATE, CREATE_OR_UPDATE, DELETE, DENY_ACCESS, DOWNLOAD, EDIT, EXECUTE, EXPORT, GIVE_ACCESS, GRANT_ACCESS, IMPORT, INSTALL, MANAGE, MOVE, OPEN, RE_INSTALL, RE_START, READ, REFRESH, REMOVE_ACCESS, RENAME, RENEW, REQUEST_TO_RESET_PASSWORD, RESET_PASSWORD, RESTORE_ACCESS_RIGHT, RESUME, RISE_EXCEPTION, RUN, SIGN_IN, SIGN_OUT, SIGN_UP, START, STOP, SUSPEND, SWITCH_CUSTOMER, SWITCH_OWNER, UPDATE,UPLOAD
}
