package lu.itrust.business.ts.model.analysis;

public enum ExportFileName {
    ACTION_PLAN, ASSET, BRAINSTORMING, DATABASE, ILR_DATA, MEASURE_COLLECTION, REPORT, RISK_ESTIMATION, RISK_REGISTER,
    RISK_SHEET_EXCEL, RISK_SHEET_WORD,
    RRF, SCENARIO, SOA
}
